# Generated by Django 2.1.3 on 2018-11-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSATU1', '0002_auto_20181108_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
